FROM node:22-alpine

RUN apk add --no-cache openssl
RUN corepack enable && corepack prepare pnpm@10.22.0 --activate

WORKDIR /usr/src/app

# Copy lockfile and package.json to cache dependencies
COPY package.json pnpm-lock.yaml ./

# Install dependencies using frozen-lockfile
RUN pnpm install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Generate Prisma Client
RUN pnpm db:generate

EXPOSE 3000

CMD ["pnpm", "dev"]
