services:
  kallisto-api:
    image: ${DOCKER_HUB_USERNAME:-aidrinperaira}/kallisto-nexus:${IMAGE_TAG:-latest}
    container_name: kallisto-api-prod
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
