services:
  kallisto-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kallisto-api-dev
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevents local node_modules from overwriting container's
    restart: always
    extra_hosts:
      - "localhost:host-gateway"

  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: kallisto_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-kallisto}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
