import { ItemEntity } from "@src/modules/kallisto-hub/domain/entities/ItemEntity";
import { IItemRepository } from "@src/modules/kallisto-hub/application/interfaces/repositories/IItemRepository";
import {
  CreateItemRequestDTO,
  ItemResultDTO,
} from "@src/modules/kallisto-hub/application/dto/ItemDTO";
import { ICreateItemUseCase } from "@src/modules/kallisto-hub/application/interfaces/usecases/item/ICreateItemUseCase";

export class CreateItemUseCase implements ICreateItemUseCase {
  constructor(private readonly _itemRepository: IItemRepository) {}

  async execute(dto: CreateItemRequestDTO): Promise<ItemResultDTO> {
    const now = new Date();
    const item: ItemEntity = {
      id: "", // Generated by repository/DB
      itemCode: "", // Generated by repository/DB
      name: dto.name,
      category: dto.category,
      hsnCode: dto.hsnCode,
      imageUrl: dto.imageUrl,
      unitOfMeasure: dto.unitOfMeasure,
      description: dto.description,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      specifications: dto.specifications.map((s) => ({
        id: "",
        specName: s.specName,
        specValues: s.specValues,
        itemId: "",
      })),
    };

    const created = await this._itemRepository.create(item);

    return {
      id: created.id,
      itemCode: created.itemCode,
      name: created.name,
      category: created.category,
      hsnCode: created.hsnCode,
      imageUrl: created.imageUrl,
      unitOfMeasure: created.unitOfMeasure,
      description: created.description,
      isActive: created.isActive,
      specifications: created.specifications?.map((s) => ({
        id: s.id,
        specName: s.specName,
        specValues: s.specValues,
      })),
    };
  }
}
