export interface IRefreshTokenUseCase {
  /**
   * Refreshes the access token and session token.
   * Session is to be refreshed by auth service and then the new access token is
   * to be generated by checking the user repository.
   * @param accessToken expired access token from client
   * @param sessionToken active session token from client
   */
  execute(
    accessToken: string,
    sessionToken: string,
  ): Promise<{ sessionToken: string; accessToken: string }>;
}
