export enum VendorType {
  AUTHORIZED_DEALER = "AUTHORIZED_DEALER",
  DISTRIBUTOR = "DISTRIBUTOR",
  WHOLESALER = "WHOLESALER",
  RETAILER = "RETAILER",
  STOCKIST = "STOCKIST",
}

export enum MaterialCategory {
  DOOR = "DOOR",
  WINDOW = "WINDOW",
  STRUCTURAL_STEEL = "STRUCTURAL_STEEL",
  CEMENT_AND_CONCRETE = "CEMENT_AND_CONCRETE",
  AGGREGATES = "AGGREGATES",
  BRICKS_AND_MASONRY = "BRICKS_AND_MASONRY",
  ROOFING = "ROOFING",
  FLOORING = "FLOORING",
  PLUMBING = "PLUMBING",
  ELECTRICAL = "ELECTRICAL",
  INSULATION = "INSULATION",
  HARDWARE_AND_FITTINGS = "HARDWARE_AND_FITTINGS",
  GLASS = "GLASS",
  TIMBER_AND_WOOD = "TIMBER_AND_WOOD",
  PAINTS_AND_COATINGS = "PAINTS_AND_COATINGS",
  WATERPROOFING = "WATERPROOFING",
  SAFETY_AND_PPE = "SAFETY_AND_PPE",
}

export enum UnitOfMeasure {
  NOS = "NOS",
  SQM = "SQM",
  SQFT = "SQFT",
  RMT = "RMT",
  KG = "KG",
  TON = "TON",
  BAG = "BAG",
  LITRE = "LITRE",
  BUNDLE = "BUNDLE",
  BOX = "BOX",
  SET = "SET",
}

export enum ProductStatus {
  ACTIVE = "ACTIVE",
  DISCONTINUED = "DISCONTINUED",
  OUT_OF_STOCK = "OUT_OF_STOCK",
  COMING_SOON = "COMING_SOON",
}
