import { IPortfolioProjectRepository } from "@src/modules/kallisto-bridge/application/interfaces/repositories/portfolio/IPortfolioProjectRepository";
import { IPortfolioRepository } from "@src/modules/kallisto-bridge/application/interfaces/repositories/portfolio/IPortfolioRepository";
import { PortfolioProjectEntity } from "@src/modules/kallisto-bridge/domain/entities/PortfolioEntity";
import { AddPortfolioProjectUseCase as IAddPortfolioProjectUseCase } from "@src/modules/kallisto-bridge/application/interfaces/usecases/portfolio/IAddPortfolioProjectUseCase";
import { AddPortfolioProjectRequestDTO } from "@src/modules/kallisto-bridge/application/dto/usecases/PortfolioDTO";
import { AppError, ErrorCode } from "@packages/common/errors";
import { HttpStatus } from "@packages/common/enums";
import { ProfileMessages } from "@packages/common/messages";

export class AddPortfolioProjectUseCase implements IAddPortfolioProjectUseCase {
  constructor(
    private readonly _portfolioProjectRepository: IPortfolioProjectRepository,
    private readonly _portfolioRepository: IPortfolioRepository,
  ) {}

  async execute(request: AddPortfolioProjectRequestDTO): Promise<void> {
    // 1. Check if Portfolio exists
    const existingPortfolio = await this._portfolioRepository.findById(
      request.portfolioId,
    );

    if (!existingPortfolio) {
      throw new AppError(
        ErrorCode.PORTFOLIO_NOT_FOUND,
        ProfileMessages.PORTFOLIO_NOT_FOUND,
        HttpStatus.NOT_FOUND,
      );
    }

    // 2. Create new Portfolio Project
    const now = new Date();
    const projectData: PortfolioProjectEntity = {
      id: "", // ID will be generated by the repository/DB
      portfolioId: request.portfolioId,
      projectName: request.projectName,
      location: request.location,
      projectType: request.projectType,
      scope: request.scope,
      completionYear: request.completionYear,
      budgetValue: request.budgetValue,
      budgetCurrency: request.budgetCurrency || "INR",
      thumbnailUrl: request.thumbnailUrl,
      photos: request.photos,
      isKallistoVerified: request.isKallistoVerified,
      testimonialClientName: request.testimonialClientName,
      testimonialClientPhone: request.testimonialClientPhone,
      testimonialText: request.testimonialText,
      createdAt: now,
      updatedAt: now,
    };

    await this._portfolioProjectRepository.create(projectData);
  }
}
