import { IPortfolioRepository } from "@src/modules/kallisto-bridge/application/interfaces/repositories/portfolio/IPortfolioRepository";
import { IPortfolioProjectRepository } from "@src/modules/kallisto-bridge/application/interfaces/repositories/portfolio/IPortfolioProjectRepository";
import { IServiceProviderRepository } from "@src/modules/kallisto-bridge/application/interfaces/repositories/profile/IServiceProviderRepository";
import {
  PortfolioEntity,
  PortfolioProjectEntity,
} from "@src/modules/kallisto-bridge/domain/entities/PortfolioEntity";
import { CreatePortfolioUseCase as ICreatePortfolioUseCase } from "@src/modules/kallisto-bridge/application/interfaces/usecases/portfolio/ICreatePortfolioUseCase";
import {
  AddPortfolioProjectRequestDTO,
  CreatePortfolioRequestDTO,
  CreatePortfolioResponseDTO,
} from "@src/modules/kallisto-bridge/application/dto/usecases/PortfolioDTO";
import { AppError, ErrorCode } from "@packages/common/errors";
import { HttpStatus } from "@packages/common/enums";
import { ProfileMessages } from "@packages/common/messages";

export class CreatePortfolioUseCase implements ICreatePortfolioUseCase {
  constructor(
    private readonly _portfolioRepository: IPortfolioRepository,
    private readonly _portfolioProjectRepository: IPortfolioProjectRepository,
    private readonly _serviceProviderRepository: IServiceProviderRepository,
  ) {}

  async execute(
    dto: CreatePortfolioRequestDTO & AddPortfolioProjectRequestDTO,
  ): Promise<CreatePortfolioResponseDTO> {
    // 1. Check if Service Provider exists
    const existingSp = await this._serviceProviderRepository.findById(
      dto.serviceProviderId,
    );

    if (!existingSp) {
      throw new AppError(
        ErrorCode.VALIDATION_ERROR,
        ProfileMessages.PROFILE_NOT_FOUND,
        HttpStatus.NOT_FOUND,
      );
    }

    // 2. Check if a Portfolio already exists for this SP (1-1 relationship)
    const existingPortfolio =
      await this._portfolioRepository.findByServiceProviderId(
        dto.serviceProviderId,
      );

    if (existingPortfolio) {
      throw new AppError(
        ErrorCode.PORTFOLIO_ALREADY_EXISTS,
        ProfileMessages.PORTFOLIO_ALREADY_EXISTS,
        HttpStatus.CONFLICT,
      );
    }

    // 3. Create new Portfolio
    const now = new Date();
    const portfolioData: PortfolioEntity = {
      id: "", // ID will be generated by the repository/DB
      serviceProviderId: dto.serviceProviderId,
      portfolioWebsite: dto.portfolioWebsite,
      isPublic: dto.isPublic,
      createdAt: now,
      updatedAt: now,
    };

    const newPortfolio = await this._portfolioRepository.create(portfolioData);

    // 4. Update Service Provider entry
    await this._serviceProviderRepository.update({
      id: dto.serviceProviderId,
      isPortfolioAdded: true,
      portfolioId: newPortfolio.id,
    });

    // 5. Create initial Portfolio Project
    const projectData: PortfolioProjectEntity = {
      id: "", // ID will be generated by the repository/DB
      portfolioId: newPortfolio.id,
      projectName: dto.projectName,
      location: dto.location,
      projectType: dto.projectType,
      scope: dto.scope,
      completionYear: dto.completionYear,
      budgetValue: dto.budgetValue,
      budgetCurrency: dto.budgetCurrency || "INR",
      thumbnailUrl: dto.thumbnailUrl,
      photos: dto.photos,
      isKallistoVerified: dto.isKallistoVerified || false,
      testimonialClientName: dto.testimonialClientName,
      testimonialClientPhone: dto.testimonialClientPhone,
      testimonialText: dto.testimonialText,
      createdAt: now,
      updatedAt: now,
    };

    await this._portfolioProjectRepository.create(projectData);

    return {
      portfolioId: newPortfolio.id,
    };
  }
}
